version: '3'

services:
  app:
    build:
      context: .
    image: annabogacheva/crypto_api:latest
    restart: unless-stopped
    container_name: api
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      sql_password: "${sql_password}"
      binance_api_key: "${binance_api_key}"
      binance_api_secret: "${binance_api_secret}"
      ftx_api_key: "${ftx_api_key}"
      ftx_api_secret: "${ftx_api_secret}"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"

