global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: "app"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    dns_sd_configs:
      - names: ["app"]
        port: 8080
        type: A
        refresh_interval: 5s