name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: sqlpass
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Install MySQL
      run: |
        sudo apt update
        sudo apt install mysql-server
        sudo service mysql start
        sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
    - name: Test
      env:
        binance_api_key: ${{ secrets.BINANCE_API_KEY }}
        binance_api_secret: ${{ secrets.BINANCE_API_SECRET }}
        ftx_api_key: ${{ secrets.FTX_API_KEY }}
        ftx_api_secret: ${{ secrets.FTX_API_SECRET }}
        sql_password: 'sqlpass'
      run: |
        python api.py &
        sleep 5
        cat logs/API.log
        cat logs/ListenerManager.log
        pytest
        cat logs/binance_BNBBTC.log

